# Generated by Django 3.2.5 on 2022-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pg',
            name='state',
        ),
        migrations.AddField(
            model_name='pg',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
