# Generated by Django 3.2.5 on 2022-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('new_name', models.CharField(max_length=30)),
                ('new_email', models.EmailField(max_length=254)),
                ('new_address', models.CharField(max_length=50)),
                ('new_phonenumber', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
